// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ArticleItem: typeof import('./components/articles/list/article-item.vue')['default']
    ArticleRank: typeof import('./components/articles/list/article-rank.vue')['default']
    ArticleType: typeof import('./components/articles/list/article-type.vue')['default']
    ContentBanner: typeof import('./components/articles/content/content-banner.vue')['default']
    ContentInfo: typeof import('./components/articles/content/content-info.vue')['default']
    ContentMain: typeof import('./components/articles/content/content-main.vue')['default']
    Footer: typeof import('./components/layouts/footer.vue')['default']
    GameInfo: typeof import('./components/game/content/game-info.vue')['default']
    GameItem: typeof import('./components/game/list/game-item.vue')['default']
    GameRemark: typeof import('./components/game/content/game-remark.vue')['default']
    GameType: typeof import('./components/game/list/game-type.vue')['default']
    Header: typeof import('./components/layouts/header.vue')['default']
    UserInfo: typeof import('./components/user/user-info.vue')['default']
  }
}

export { }
