// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ArticleItem: typeof import('./components/articles/list/article-item.vue')['default']
    ArticleRank: typeof import('./components/articles/list/article-rank.vue')['default']
    ArticleType: typeof import('./components/articles/list/article-type.vue')['default']
    ContentBanner: typeof import('./components/articles/content/content-banner.vue')['default']
    ContentInfo: typeof import('./components/articles/content/content-info.vue')['default']
    ContentMain: typeof import('./components/articles/content/content-main.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Footer: typeof import('./components/layouts/footer.vue')['default']
    GameInfo: typeof import('./components/game/content/game-info.vue')['default']
    GameItem: typeof import('./components/game/list/game-item.vue')['default']
    GameRemark: typeof import('./components/game/content/game-remark.vue')['default']
    GameType: typeof import('./components/game/list/game-type.vue')['default']
    Header: typeof import('./components/layouts/header.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    UserInfo: typeof import('./components/user/user-info.vue')['default']
  }
}

export { }
